name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/royal-app:latest, ${{ secrets.DOCKERHUB_USERNAME }}/royal-app:${{ github.sha }}
      
  deploy:
      needs: build  # Specifies that the `deploy` job depends on the `build` job
      runs-on: self-hosted

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSssssH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@3.87.86.168 'sudo docker pull jcmachado86/royal-app:latest'

      - name: Stop running container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@3.87.86.168 'sudo docker stop royal-app || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@3.87.86.168 'sudo docker rm royal-app || true'

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@3.87.86.168 'sudo docker run -d --name royal-app -p 3000:3000 jcmachado86/royal-app:latest'

      - name: Set timestamp
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Handle failures
        if: ${{ failure() }}
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")" - ${{ github.repository }}
        #run: echo"::set-output name=date::$(date+'%Y/%m/%d') - ${{ github.repository }}"
        #run: echo"::set-output name=date::$(date+)   ${{env.NOW}} - ${{ github.repository }}"