name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }
      - name: Build and push Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/royal-app:latest .
          docker push $DOCKERHUB_USERNAME/royal-app:latest
